#ifndef VENTURA_VERSION_HPP
#define VENTURA_VERSION_HPP

#define VENTURA_MAJOR_VERSION 0
#define VENTURA_MINOR_VERSION 2
#define VENTURA_PATCH_VERSION 0

#define VENTURA_MAKE_VERSION(major, minor, patch) ((((major * 100) + minor) * 100) + patch)
#define VENTURA_VERSION VENTURA_MAKE_VERSION(VENTURA_MAJOR_VERSION, VENTURA_MINOR_VERSION, VENTURA_PATCH_VERSION)

#endif
